# Generated by Django 4.0.6 on 2022-07-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='blog',
            name='excerpt',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
